name: Clang Format Checker
on: [push]
jobs:
  clang-format-checking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: DoozyX/clang-format-lint-action@v0.17
        with:
          sources: "DarkroomTimer"
          extensions: 'h,cpp,c,ino'
          clangFormatVersion: 17
